### PR TITLE
Proposal: support for dynamic linear systems

### PR DESCRIPTION
**Pull request by cstjean**
I'd like to use this package for modeling a dynamic linear system (of which recursive least square is a special case), as in Shumway and Stoffer. As is, this cannot be done, because the way the math works out, I need to have the observation matrix H change from time step to time step. 

First question, are you interested in supporting this use case at all? I thank you very much for putting this package online, it's helped me a lot, but perhaps you might feel that this PR is out-of-scope...

If yes, then we can discuss how best to implement this. This PR is a minimally-invasive modification of the code to support it, but it's not terribly elegant. If you have any suggestion, I can refactor the code. And of course, this is missing documentation and testing, pending your approval of the general approach.

RLS demo:

```julia
rng = MersenneTwister(1)
x0 = [20., 20.]
P0 = eye(2) .* 1000

Phi = [1.0 0.0; 
       0.0 1.0]
b = zeros(2)
Q = [0.0 0.0; 
     0.0 0.0]

y = [NaN]
H = [10 100]
sig2 = 1
R = eye(1)*sig2*100
M = LinearHomogSystem(x0, P0, Phi, b, Q, y, H, R)

N = 100
# Define linear regression problem
XX = hcat(ones(1,1,N), rand(rng, 1, 1, N))
YY = 7*xx[:] + randn(rng, N)*sqrt(sig2)+15

kalmanfilter(YY', M, XX)[1]
```

The final values are (approximately) the same as `XX[1, :, :]' \ YY`

### CODE REVIEW

**Comment by mschauer** [comment]
> First question, are you interested in supporting this use case at all? I thank you very much for putting this package online, it's helped me a lot, but perhaps you might feel that this PR is out-of-scope...

This is my favourite outcome, I am very happy if this is useful and stimulates further development, please extend and propose any adaption which makes this more useful to you and others.

 I was thinking of splitting the dynamic model and the observation model into to two different structs, so you can combine them more freely. But I think you want would be best handled by a new type 
which overloads
```julia
function observe!(s, x, P, t, Y, M::InhomogObsSystem)
    y, H, R = Y    
    t, y, H, R
end
```
In my wisdom ;-) I allow observe! to unpack any argument `Y` to obtain specific `y, H` and `R` and this is exactly the situation where you want to use this.

**Comment by cstjean** [comment]
Cool!

> I was thinking of splitting the dynamic model and the observation model into to two different structs, so you can combine them more freely

The thing is that it's not just the observation model that can vary. According to Murphy's textbook (or [wikipedia](https://en.wikipedia.org/wiki/Kalman_filter#Underlying_dynamical_system_model)), every matrix in the system (i.e. the transition matrix, the noise matrices etc.) can vary arbitrarily with time in a Kalman filter, so for fully general dynamics, there would be no `struct`; we would merely pass all input matrices to `kalmanfilter!` (whether separately, or packed together in `Y` like you suggest). I actually need a time-varying `b` for my project, so it's not just a theoretical interest!

Also, since the current time-homogeneous model is a special case of the time-inhomogeneous model, it would be nice to implement it as such. 

What do you think?

**Comment by mschauer** [comment]
Some questions: Do you know the time-varying `b` beforehand? Is it a function or a set of measurements? Or does it depend on the state or on the observations?

**Comment by cstjean** [comment]
> Do you know the time-varying b beforehand?

In my case, yes. I believe that for the theory to work, `b` has to be a given (independent of the hidden state), otherwise it wouldn't be a linear dynamical system. Right?

**Comment by cstjean** [comment]
In fact... I'm interested in this formulation

`x[k] = Φx[k−1] + B[k]u[k] + w[k]`

where u is a given control signal. However, since B and u are both given, I'm assuming that it's equivalent to supporting

`x[k] = Φx[k−1] + b[k] + w[k]`

with `b[k] := B[k]u[k]`

**Pull request closed without merging**
